# Generated by Django 5.0.6 on 2024-05-09 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answers', models.CharField(max_length=1)),
                ('Correct_Answers', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_areas', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='participation', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('Class_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('School_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('year_level', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=100)),
                ('Subject_score', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sydney_participants', models.IntegerField()),
                ('sydney_percentile', models.FloatField()),
                ('Correct_answer_percentage_per_class', models.FloatField()),
                ('Correct_Answer', models.CharField(max_length=255)),
                ('Participant', models.CharField(max_length=50)),
                ('Student_score', models.FloatField()),
                ('Category_Id', models.CharField(max_length=100)),
                ('Year_Level_name', models.CharField(max_length=10)),
                ('Correct_Answer_Id', models.CharField(max_length=20)),
                ('Answer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.answers')),
                ('Assessment_Areas_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.assessment_areas')),
                ('Award_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.awards')),
                ('Class_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.class')),
                ('School_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.school')),
                ('Student_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.student')),
                ('Subject_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.subject')),
            ],
        ),
    ]
